apiVersion: v1
kind: Service
metadata:
  name: akkluster-http
spec:
  selector:
    app: akkluster
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  name: akkluster-management
spec:
  selector:
    app: akkluster
  type: NodePort
  ports:
    - name: management
      port: 8558
      targetPort: management

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: akkluster
spec:
  replicas: 2
  template:
    metadata:
      name: akkluster
      labels:
        app: akkluster
    spec:
      containers:
      - name: akkluster
        image: hseeberger/akkluster:latest
        imagePullPolicy: IfNotPresent
        args: [
#          "-Dakka.cluster.downing-provider-class=rocks.heikoseeberger.akkluster.NaiveDowningProvider"
        ]
        ports:
        - name: http
          containerPort: 80
        - name: management
          containerPort: 8558
        - name: akka-remote
          containerPort: 25520
        securityContext:
          capabilities:
            add:
            - NET_ADMIN

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
